version: '3.7'

networks:
  api:
  db:

services:
  api:
    build: .
    image: api-livraria
    links:
      - "db"
    networks:
      - api
      - db
    ports:
      - "3000:3000"
    restart: on-failure
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: livraria
    ports:
      - 5432:5432
    networks:
      - db
      - api
    restart: on-failure